// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Preferences } from '@capacitor/preferences';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// --- YENİ GÜVENLİ KASA (NATIVE STORAGE ADAPTER) ---
// Bu custom adapter, Supabase'e localStorage yerine Capacitor Preferences'ı
// kullanmasını söyler.
const customStorageAdapter = {
  getItem: async (key: string) => {
    const { value } = await Preferences.get({ key });
    return value;
  },
  setItem: async (key: string, value: string) => {
    await Preferences.set({ key, value });
  },
  removeItem: async (key: string) => {
    await Preferences.remove({ key });
  },
};

// Supabase istemcisini, custom "Güvenli Kasa"mızı kullanarak oluşturuyoruz.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorageAdapter, //localStorage yerine bunu kullan
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});