// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okztpvlipwlgciwspdnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9renRwdmxpcHdsZ2Npd3NwZG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDAwMjksImV4cCI6MjA2NzkxNjAyOX0.ysXO5GKD4UMKlLyoWuZvQl7DUHEZc5MWzqokdlwmH_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});